apiVersion: v1
kind: Pod
metadata:
  name: envoy-test
  labels:
    app: envoy-pod
spec:
  #nodeName: worker2-k8sho
  containers:
  - name: envoy
    image: envoyproxy/envoy-dev:f08b17516026882a0964a225c0135dc996b964af
    volumeMounts:
    - mountPath: /etc/envoy/envoy.yaml
      name: proxy
  volumes:
  - name: proxy
    hostPath: 
      path: /root/envoy.yaml 
      type: FileOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-svc
spec:
  selector:
    app: envoy-pod
  type: NodePort
  ports:
  - port: 10000
    targetPort: 10000
    nodePort: 30055
